version: '3.1'

services:
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    volumes:
     - ./data:/data/db
    ports:
      - '27017:27017'

  api:
    container_name: service
    build: ./backend
    ports:
      - '3001:3001'
    depends_on:
      - mongo
    links:
      - mongo

  website:
    container_name: website
    build: ./frontend
    ports:
      - '4200:4200'
    depends_on:
      - mongo
      - api
